### ISSUE TITLE
update engines

### ISSUE THREAD

**Issue by whitetown** [Four-Lights-NL/strapi-plugin-deepcopy#71]
could you please update the engine?
`@fourlights/strapi-plugin-deep-copy@1.0.2: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.11.1"`
I think there is no strict dependency on it

**Comment by trijpstra-fourlights** [comment]
I've removed the upper limit on the node engine and published a new version.

Please note that work on this plugin has stalled and I haven't tested if it works on Strapi versions later than v4.12.7.

Feel free to make a new issue if you encounter any problems though.
